### ISSUE TITLE
which php

### ISSUE THREAD

**Issue by billynoah** [farico/sequelpro_bundles#3]
This is more a comment than an issue but I think it would be good to mention in the installation instructions:
- Make sure you have mcrypt extension installed.  I did not and needed to run `brew install php55-mcrypt` since I am using homebrew.
- Make sure you call the correct version of php in the bundle.  I ran `which php` to find out and then changed the first line to `#!/usr/local/bin/php` to work with homebrew

**Comment by farico** [comment]
Hi,

thank you for your comment, I will update installation instructions as you suggest.

**Comment by billynoah** [comment]
Thanks for the great bundle! I was using JSON before and converting to array before I found yours.

**Comment by farico** [comment]
I am glad to help! Has this problem too. I have edited both readme and script itself as you suggested. Thank you!
